### ISSUE TITLE
Add data from Offsetting Deals

### ISSUE THREAD

**Issue by dirkpieper** [OpenAPC/openapc-de#105]
More and more institutions are negotiating offsetting deals, which include the opportunity to publish OA articles for participating institutions. Those articles have a price information (e.g. the Springer Open Choice price). To be able to record and collect this information and in order not to distort the statistical analysis I want to suggest to expand the Open APC schema by a column called "is_offsetting".

**Comment by tullney** [comment]
As discussed during the workshop, I suggest to not add such a column. We have various reasons for discounted prices - some of which are institution-based (central billing agreements, offsetting models), some of which are author-based (individual waivers, negotiations on a case-to-case basis, author's doing peer review for the journal in question, etc.). I don't think it's useful to single out offsetting contracts. In addition, it's crucial to Open APC initiative's success to keep the data submission as simple as possible, and telling if a particular article has been handled under a offsetting agreement is not so easy.

Data contributors should be asked to disclose special conditions (DFG funding, offsetting deals, etc.) on their README.md (see #59) as a first step. Possible other ways to achieve the goal: start another repository under the OpenAPC umbrella or encourage contributors to provide more information in their /data folders.

**Comment by cbroschinski** [comment]
As @tullney suggested, another [separate dataset](https://github.com/OpenAPC/openapc-de/tree/master/data/offsetting) was created to collect offsetting data (At the moment, only information on Springer Compact publications is collected without pricing information). In general I agree with the argument of keeping the submission process and the data schema as simple as possible to encourage participation in OpenAPC.
