### ISSUE TITLE
Register every version of the dataset

### ISSUE THREAD

**Issue by vpeil** [OpenAPC/openapc-de#108]
Since we track versions of the dataset it would be very useful to make every version **citable**.

So here's how it might work:
1. git tag ... sets a new version (already done)
2. produce metadata XML (with updated list of contributors)
3. push metadata & register DOI (version number in DOI?)

**Comment by tullney** [comment]
By all means: let's do this. At the moment, the best way to cite is using the existing GitHub releases (e.g. https://github.com/OpenAPC/openapc-de/tree/v2.1.13). Having these versions archived and accessible via DOI would pose a great improvement. I don't care so much about putting semantic meaning into the DOI (regarding your third point, @vpeil).

**Comment by tullney** [comment]
Using the commit hash to generate the DOI might be a feasible approach indeed. Sounds easier and more secure than using the tag.

**Comment by jbartlewski** [comment]
Our latest data release can always be accessed via the following DOI:

[10.5281/zenodo.6883472](https://doi.org/10.5281/zenodo.6883472)
