### ISSUE TITLE
Add a new column for an identifier for institutional agreements

### ISSUE THREAD

**Issue by adrsik** [OpenAPC/openapc-de#128]
It would be very helpful if we could add a new column for an identifier for institutional agreements.
The identifier would help to bundle articles where the publisher adds inconsistent and different publisher data (names) to Crossref.

**Comment by cbroschinski** [comment]
As discussed in connection with offsetting deals (see #105), we should restrain ourselves from overextending the data schema. Institutional agreements, along with issues like central billing agreements or offsetting deals, should instead be described in the institutional README files. The case of inconsistent designations in crossref metadata persists, but we are able to deal with it via automated normalisation in the [enrichment routines](https://github.com/OpenAPC/openapc-de/blob/2.11.0/python/openapc_toolkit.py#L676-L681).
