### ISSUE TITLE
2023 APC information from DOAJ's largest 19 publishers 

### ISSUE THREAD

**Issue by dommitchell** [OpenAPC/openapc-de#1534]
Sharing here in case it is of use.

[Complete-20230614T073608Z-001.zip](https://github.com/OpenAPC/openapc-de/files/11758622/Complete-20230614T073608Z-001.zip)

**Comment by cbroschinski** [comment]
Interesting data set, but unfortunately that's nothing we can make use of. The idea of OpenAPC is to aggregate APC **costs** directly from the institutions which paid them, while the amounts listed on publishers' sites (or the DOAJ) are **list prices**. There are many factors which may have an influence on those, usually leading to somewhat lower amounts paid in the end.
