### ISSUE TITLE
adding ROR ID for metadata element institution

### ISSUE THREAD

**Issue by AnMarlen** [OpenAPC/openapc-de#1917]
Hello
We would like to suggest complementing the metadata schema with the ROR ID of the institution reported as payer. At the moment, the “institution”-element is just plain text choosen by the reporting institution. 
With adding the ROR ID OpenAPC data could be reused and further enriched more seamlessly in combination with other open scholarly metadata such as from OpenAlex. E.g. Open Alex already included information on paid prices from OpenAPC but without the payer information (https://docs.openalex.org/api-entities/works/work-object#apc_paid).

**Comment by cbroschinski** [comment]
That is already the case: We utilize a table of [institutional metadata](https://github.com/OpenAPC/openapc-de/blob/master/data/institutions.csv) which contains the ROR ID alongside other information. To make use of it, you would have to join the table with one of our main datasets on the "institution" field.
However, I can see that this information is somewhat hidden at the moment, I think we will add a hint to our main README file.
