### ISSUE TITLE
Update DOI links to use HTTPs

### ISSUE THREAD

**Issue by ioverka** [OpenAPC/openapc-de#226]
Background: https://www.crossref.org/blog/linking-dois-using-https-the-background-to-our-new-guidelines/

probably relevant for the treemaps website, e.g. https://treemaps.intact-project.org/apcdata/openapc/#journal/Nature%20Communications/Imperial%20College%20London/

Greetings from Munich,
inga

**Comment by cbroschinski** [comment]
Thanks for the hint, the DOI links on the treemaps site will now all use HTTPS (and we also removed the outdated 'dx' subdomain from all links)
