### ISSUE TITLE
[data] FP7 post-grant Open Access publishing funds pilot 

### ISSUE THREAD

**Issue by jibe-b** [OpenAPC/openapc-de#333]
Are the publications funded by the FP7 post-grant Open Access publishing funds pilot used as a source of data?

source: https://www.openaire.eu/postgrantoapilot

**Comment by cbroschinski** [comment]
Indeed they are, see [here](https://github.com/OpenAPC/openapc-de/blob/master/data/openaire/OpenAIRE_OpenAPC_dataset_201611-1_enriched.csv) and [here](https://treemaps.intact-project.org/apcdata/openaire/) for a visualisation. However, the data is not complete yet. We expect to receive the remaining publications from 2016 within the next weeks.
