### ISSUE TITLE
Update contributor guidelines

### ISSUE THREAD

**Issue by njahn82** [OpenAPC/openapc-de#48]
Many contributors find the guidelines for data sharing unclear. Because the guidelines are available in German only, it is hard to share our approach with related non-German-speaking initiatives.

**Comment by njahn82** [comment]
maybe @moreedri can also help?

**Comment by tullney** [comment]
Let's update this issue or file another issue to also cover: make everything available in English and in German. Contributors list, citation information etc. are only in English so far.

**Comment by njahn82** [comment]
:+1:

**Comment by moreedri** [comment]
Indeed, I have some drafts ready for project rationale and practical operations.

Would you put the translation in a different folder, maybe /openapc-en/, or use file extensions?

There is some duplication between the files, worth discussing how to handle that?



Dries

Najko Jahn <notifications@github.com>schreef:



maybe @moreedri<https://github.com/moreedri> can also help?

-

**Comment by njahn82** [comment]
Great,+ @moreedri . In the end, can we have something similar to 

https://github.com/ropensci/taxize/blob/master/CONTRIBUTING.md

and refer to a German version in the wiki?
 
Can you just paste your drafts to the wiki.

**Comment by cbroschinski** [comment]
The [german data submission guidelines](https://github.com/OpenAPC/openapc-de/wiki/Handreichung-Dateneingabe) have been updated to reflect the changes OpenAPC has undergone in the recent months. Based on this new version an english translation has been created: https://github.com/OpenAPC/openapc-de/wiki/Data-Submission-Handout
