### ISSUE TITLE
State data constraints explicitly in README

### ISSUE THREAD

**Issue by csarven** [OpenAPC/openapc-de#624]
In the summary of both fully OA and hybrid OA:

* State the time (period) that the averages are based on.
* State minimum and maximum.

**Comment by csarven** [comment]
If anyone would like to verify based on https://github.com/OpenAPC/openapc-de/raw/406b4fec59e01ca7602f6ee511bac9a7daee4c59/data/apc_de.csv

For 2018 (both full and hybrid):
* Min: 13
* Max: 12000
* Mean: 1834.364

Full:
* Min: 13
* Max: 12000
* Mean: 1614.201

Hybrid:
* Min: 17.70
* Max: 6296
* Mean: 2550.646

**Comment by tullney** [comment]
This could be done by introducing two similar new tables in https://github.com/OpenAPC/openapc-de/blob/master/README.Rmd after the first paragraph of the full/hybrid sections. This way it gets updated every time the README is generated.

|   | 2015  | 2016  | 2017  | 2018  |
|---|---|---|---|---|
|  mean |   |   |   |   |
|  median |   |   |   |   |
|  min |   |   |   |   |
|  max |   |   |   |   |

**Comment by tullney** [comment]
@cbroschinski , what do you think? I know that document is getting longer and longer, but this should be a) interesting information and b) easy to add to the document.

**Comment by tullney** [comment]
And @csarven, I think it's till good to have the mean values for the complete dataset. There are sample analyses with a more detailed view, and people are always able to work with the data themselves. Besides APC trends (it's getting more expensive) we also have biases coming from a smaller number of articles covered in previous years, so the overall mean values are not the most accurate information. But if we talk about how many articles and how much money is covered, we should also tell people about the basic statistic data.

**Comment by csarven** [comment]
Related to introducing two new tables: All tables and figures should link to versioned data...

**Comment by cbroschinski** [comment]
Sounds resonable, although I'm not convinced there's much to learn from the min/max numbers (even if they are correct, there's usually some special cicrumstances involved). Will figure something out in the next days.

**Comment by csarven** [comment]
@tullney Certainly. I fear that lumping values across periods speaks something completely different than what's actually comparable.

@cbroschinski Certainly. Still important to indicate the "circumstances" so that data consumers are aware eg. constraints for how the values can be used and communicated.
