### ISSUE TITLE
Implement new Open APC schema

### ISSUE THREAD

**Issue by cbroschinski** [OpenAPC/openapc-de#66]
The updated open apc schema should be implemented. This will require renaming some of the existing column heads, changing their order and deleting deprecated columns.

**Comment by tullney** [comment]
@cbroschinski , are you going to do that for all data sets? Please let me know if you need a hand…

**Comment by cbroschinski** [comment]
@tullney, no, just for the main file, which is now converted. But thanks for the offer!
