### ISSUE TITLE
Issue running the code

### ISSUE THREAD

**Issue by waheed13085** [OpenAPC/openapc-de#703]
![OpenAPC_01](https://user-images.githubusercontent.com/18336848/69212261-de7a7a00-0b71-11ea-8441-6e9f91279706.png)
When I run the code it give the following message
"No hosts found. Please specify (single) host string for connection:"

Any idea what should I do

**Comment by cbroschinski** [comment]
Please have a look at my answer [here](https://github.com/OpenAPC/openapc-de/issues/667#issuecomment-520763978). This code is tailored to work in a very specific environment at our institution and won't be of any use to you.
