### ISSUE TITLE
Where's the data dictionary ? 

### ISSUE THREAD

**Issue by cdemay** [OpenAPC/openapc-de#707]
I'm having trouble to understand OpenAPC's databases... Without the data dictionary, I don't really understand what defines every single entry and every variable. Is there any document I missed ? Thanks a lot

**Comment by cbroschinski** [comment]
You can find the definition of  the OpenAPC data schema in our [wiki](https://github.com/OpenAPC/openapc-de/wiki/schema). You may also want to have a look at our [data submission guidelines](https://github.com/OpenAPC/openapc-de/wiki/Data-Submission-Handout) for more info on how the cost values should be interpreted.
