### ISSUE TITLE
API data does not match treemap data

### ISSUE THREAD

**Issue by mpjashby** [OpenAPC/openapc-de#719]
Hi,

I'm trying to get details of all the APCs paid by a particular institution in a particular year. If I look at [the online treemap](https://treemaps.intact-project.org/apcdata/ucl/#publisher/period=2018) I can see that University College London (UCL) paid 1,656 APCs with a total value of €3,515,334. However, if I [query the API with the same parameters](https://olap.intact-project.org/cube/openapc/facts?cut=institution:UCL|period:2018) I get 501 records returned, showing a total value of €1,059,931.

I've tried to track the data back to source to identify any problems, but without success. The README file suggests the source of the data is the [JISC APC data collection](https://www.jisc-collections.ac.uk/APC-data-collection/) which in turn says the data should be [on FigShare](https://figshare.com/search?q=jisc%20collections&searchMode=1), but there do not appear to be any records there for 2018.

Looking through the project README file, I can't see any reason why these two values would be so different. Is there something in the documentation that I've missed?

**Comment by mmoch** [comment]
Hello,

please have a look at:
https://olap.intact-project.org

Results for JSON queries are limited to 500 records. No idea what the reason for this limit is.

**Comment by mpjashby** [comment]
Thanks! I can't see any documentation on how to request API results with an offset, so it will probably be easier to download the dataset and work with that.
