### ISSUE TITLE
Fix duplicates and malformed DOIs

### ISSUE THREAD

**Issue by njahn82** [OpenAPC/openapc-de#75]
The following articles from recent sumbissions are duplicates:

|institution  | period|doi                          |
|:------------|------:|:----------------------------|
|Heidelberg U |   2014|10.1186/1756-0500-7-613      |
|Heidelberg U |   2014|10.1186/1748-717X-9-113      |
|Konstanz U   |   2015|10.1186/s13662-015-0538-z    |
|MPG          |   2011|10.1371/journal.pone.0015582 |
|MPG          |   2011|10.1371/journal.pone.0020289 |
|MPG          |   2011|10.1371/journal.pone.0022735 |

Please also check the following malformed DOIs

|institution  | period|doi                          |
|:------------|------:|:----------------------------|
|Heidelberg U | 2014 | 10.1186/2047-783X-19-24. |
|Heidelberg U | 2014 | 10.1186/1748-717X-9-203. |

**Comment by adrsik** [comment]
I just removed the MPG duplicates.

**Comment by njahn82** [comment]
see comment

**Comment by njahn82** [comment]
Thanks!
