### ISSUE TITLE
Filterung bei Wiley-DEAL nicht korrekt

### ISSUE THREAD

**Issue by zuphilip** [OpenAPC/openapc-de#752]
Die Filterung beim Wiley-DEAL https://treemaps.intact-project.org/apcdata/deal-wiley/#institution/ zeigt aktuell neben den vier großen (realistischen) Posten auch etliche kleinere Posten:

![openapc-wiley-deal](https://user-images.githubusercontent.com/5199995/74085664-b701c200-4a7b-11ea-9ecd-b14ce12ca656.png)

Beispielsweise von Heidelberg wird nur ein Artikel https://doi.org/10.1002/pld3.116 angegeben. Dieser Artikel ist im Januar 2019 akzeptiert worden und damit nicht Teil des DEAL-Vertrags, welcher für die hybriden OA erst ab Juli 2019 in Kraft getreten ist. Kann man diese Fälle besser herausfiltern? Vielleicht könnte `published-online` von crossref-API dazu genutzt werden, was als Datum meist sehr nah am "acceptance date" zu liegen scheint. Sauberer wäre es aber die verschiedenen Fälle direkt bei der Dateneingabe voneinander zu trennen.

Es fällt auch auf, dass bei den anderen falsch zugeordneten Werten häufig ChemistryOpen als reine OA-Zeitschrift auftaucht, z.B. https://treemaps.intact-project.org/apcdata/deal-wiley/#institution/TU%20Dresden/ChemistryOpen/. Ist hier etwas durcheinander geraten?

**Comment by cbroschinski** [comment]
Doch, das ist durchaus alles richtig so. DEAL erstreckt sich ja auch auf die OA-Zeitschriften von Wiley (die erhalten einen 20%-Rabatt auf APCs), und dieser Part von DEAL gilt auch bereits seit Januar 2019. Die Treemap listet ganz bewusst alle Artikel auf, die unter DEAL publiziert wurden, nicht nur die hybriden. Wenn man nur diese haben will, kann man das ganz einfach mittels is_hybrid=TRUE filtern:
https://treemaps.intact-project.org/apcdata/deal-wiley/#institution/is_hybrid=TRUE

**Comment by zuphilip** [comment]
Oh, bitte entschuldige, da habe ich nicht genau geguckt. Irrtümlicherweise habe ich diese kleinen Werte auch als hybrides OA angenommen, aber diese sind genau die Gold OA von Wiley und dann passt dies auch mit dem DEAL.

Vielleicht kann man die Beschreibung oben auf der Seite noch etwas präzisieren? Zumindest finde ich diese schwer zu verstehen.
