### ISSUE TITLE
How to deal with 0 cost articles

### ISSUE THREAD

**Issue by vielera** [OpenAPC/openapc-de#90]
We had a case last year where the author withdrew here application to the open access fund because the apc was waived for whatever reason. For 2016 we already have a similar case. The question is, does it make sense to include these articles into openapc with 0 EUR or is it more reasonable to exclude these articles? 
Both ways make sense to me, but lead to a different view on the data. If we include articles without costs, we get a better average APC on a global per article level. In the end, one could treat zero cost like a discount that eliminates all cost instead of part of the cost - any type of discount does lower the average. On the other hand side, if we exclude these articles, we get closer to the truth looking at the per article APC that we actually do have to pay for. 
Any suggestions?

**Comment by cbroschinski** [comment]
We have clarified our policy regarding the definition of "costs". Among other rules, zero cost articles are now explicitly excluded from the OpenAPC data set:
https://github.com/OpenAPC/openapc-de/wiki/Data-Submission-Handout#definition-of-costs
